### ISSUE TITLE
About PER

### ISSUE THREAD

**Issue by Louise158** [fanyunfeng-bit/Modal-Imbalance-PMR#9]
As the paper mentioned, "In order to reduce the inhibition, there is a prototypical entropy regularization (PER) terms to slow down the convergence speed of the dominant modality." But I didn't find it in the codes. May I ask where it is implemented?

**Comment by B-Y03** [comment]
Hello, have you found the relevant code?

**Comment by B-Y03** [comment]
Hello, have you found the code related to PER?

**Comment by Louise158** [comment]
Sorry，I didn't find the code. I closed my issue only because I saw that someone had already mentioned it.

在 2024-12-14 20:20:24，B-Y03 ***@***.***> 写道：

Hello, have you found the code related to PER?

**Comment by B-Y03** [comment]
Well, thanks for your reply.
